### ISSUE TITLE
Not an issue but can the extension change it back to the old library page instead of expanding the library sidebar?

### ISSUE THREAD

**Issue by RetardedNConfused** [Sowgro/betterLibrary#1]
probably a lot of work

**Comment by Sowgro** [comment]
It is actually super easy to implement. Should I make the sidebar disappear and say "Opened in center pane", or should I leave it like the screenshot? I can't decide

![Screenshot from 2023-09-22 17-59-14](https://github.com/Sowgro/betterLibrary/assets/69283684/6dc59b81-4009-4cdd-8c07-950e9a1734ec)

**Comment by Sowgro** [comment]
I guess I should probably add a settings page and let the user decide

**Comment by RetardedNConfused** [comment]
I guess it doesn't take anything away by having both but having options would be the way to go

Thanks

**Comment by DTM96** [comment]
I just discovered Spicetify an hour ago, and I have to say, this feature is exactly what I'm looking for. I like the way it is in your screenshot, it's similar to how Spotify worked before they screwed everything up a few months ago. I want to be able to have a list of my playlists open in the side bar, but also have the grid of artists open in the main window and have that act as the main window all the time like it used to (and also not have that crappy right side bar popup with artist info everytime, but one step at a time I guess). 

I hope youre able to implement that previous suggestion, but regardless, thank you for your work!

**Comment by Sowgro** [comment]
It is still something I plan on adding, I just have not had much spare time to work on it lately. 

There is a setting under "Display" called "Show the now-playing panel at the click of play". Disabling this should stop the right sidebar from opening every time.

**Comment by Sowgro** [comment]
I decided this would be better as its own customapp. 
https://github.com/Sowgro/legacyLibrary
