### ISSUE TITLE
Feature Request seperate scaling

### ISSUE THREAD

**Issue by citizenserious** [Sowgro/betterLibrary#3]
Thank you very much for these App 😃 Makes the usability so much better again, and works like a charm.

It would be nice if the library could be scaled separately, would be especially useful in grid view I think.
I don't know if it is even possible, but I think it could be difficult so dismiss this if you think it is unnecessary for you (:

**Comment by Sowgro** [comment]
It should be possible! I will work on this tomorrow.

**Comment by bendavidi** [comment]
> It should be possible! I will work on this tomorrow.

Thank you so much for your valuable time <3

**Comment by Sowgro** [comment]
No problem! I'm glad you like it.

**Comment by Sowgro** [comment]
Done! It was really easy to implement so I decided to do it tonight.

**Comment by bendavidi** [comment]
> Done! It was really easy to implement so I decided to do it tonight.

You just made this awesome extension even more awesome
It's thanks to people like you that I love this community so much <3
