### ISSUE TITLE
Home and Search Buttons converting to Texts

### ISSUE THREAD

**Issue by Dynamixus** [Sowgro/betterLibrary#5]
![image](https://github.com/Sowgro/betterLibrary/assets/137287047/ba7acf2b-c029-43c1-9d60-a5aa439d2578)

![image](https://github.com/Sowgro/betterLibrary/assets/137287047/7d7adadf-3a3b-4199-b88c-db0821a73f92)

I have my left panel compressed to icons only, and every time I open the Library the icons convert to text.

**Comment by Sowgro** [comment]
Thanks for the bug report, I think I know what is causing this. I will take a look later this week when I have more time.
