### ISSUE TITLE
Library items disappeared + Lyrics/Marketplace/Your Library text is messed up.

### ISSUE THREAD

**Issue by Dynamixus** [Sowgro/betterLibrary#7]
![image](https://github.com/Sowgro/betterLibrary/assets/137287047/a5f5a75e-37b1-4721-abed-631403f8689a)

It was like this after the update, I did a fresh reinstall and it's still like this.
Here's my current `config-xpui.ini`
```[Patch]

[Setting]
spotify_path           = C:\Users\Xer\AppData\Roaming\Spotify
prefs_path             = C:\Users\Xer\AppData\Roaming\Spotify\prefs
current_theme          = marketplace
inject_theme_js        = 1
overwrite_assets       = 0
spotify_launch_flags   = 
check_spicetify_update = 1
color_scheme           = 
inject_css             = 1
replace_colors         = 1
always_enable_devtools = 0

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
extensions            = popupLyrics.js|shuffle+.js|webnowplaying.js
custom_apps           = marketplace|betterLibrary|lyrics-plus
sidebar_config        = 1
home_config           = 1
experimental_features = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.33.1042.g26c92729
with    = 2.35.1
```

I also do not have any marketplace items installed:
![image](https://github.com/Sowgro/betterLibrary/assets/137287047/d06eff16-26bd-4431-8940-379dfa991a84)

**Comment by shivambegin** [comment]
fixed?

**Comment by Sowgro** [comment]
Currently working on it

**Comment by Sowgro** [comment]
Alright, for the grid view, it starts with the grid size at 0, just drag the slider and they will all appear. It will remember your setting. (In the future I will either prevent this from happening or add something to the readme about it.)

![Screenshot from 2024-03-26 15-16-10](https://github.com/Sowgro/betterLibrary/assets/69283684/90e406ef-fbb2-4784-aa8d-ef053b452359)

A fix for the messed up labels will be out later today
